import "@/styles/globals.css";

import { Inter } from "next/font/google";

import BottomBar from "@/components/shared/BottomBar";
import { LeftSideBar } from "@/components/shared/LeftSideBar";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/provider/Providers";
import SignedIn from "@/provider/SignedIn";
import SignedOut from "@/provider/SignedOut";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-row">
          <Providers>
            <SignedIn>
              <LeftSideBar />
              <section className="main-container">
                <div className="w-full max-w-4xl">{children}</div>
              </section>
              <BottomBar />
            </SignedIn>
            <SignedOut>
              <section className="main-container">{children}</section>
            </SignedOut>
          </Providers>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
