import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import BottomBar from "@/components/shared/BottomBar";
import { LeftSideBar } from "@/components/shared/LeftSideBar";
import NextAuthProvider from "@/provider/SessionProvider";
import { ThemeProvider } from "@/provider/ThemeProvider";
import { TRPCReactProvider } from "@/trpc/client";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-row">
          <NextAuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TRPCReactProvider cookies={cookies().toString()}>
                <LeftSideBar />
                <section className="main-container">
                  <div className="w-full max-w-4xl">{children}</div>
                </section>
                <BottomBar />
              </TRPCReactProvider>
            </ThemeProvider>
          </NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
