import "@/styles/globals.css";

import { Inter } from "next/font/google";

import Providers from "@/provider/Providers";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const SignedIn = dynamic(() => import("@/provider/SignedIn"));
const SignedOut = dynamic(() => import("@/provider/SignedOut"));
const LeftSideBar = dynamic(() => import("@/components/shared/LeftSideBar"));
const BottomBar = dynamic(() => import("@/components/shared/BottomBar"));
const Toaster = dynamic(() => import("@/components/ui/sonner"));

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="flex flex-row">
            <SignedIn>
              <LeftSideBar />
              <section className="main-container">
                <div className="w-full max-w-4xl">{children}</div>
              </section>
              <BottomBar />
            </SignedIn>
            <SignedOut>
              <section className="main-container">{children}</section>
            </SignedOut>
            <Toaster />
          </main>
        </Providers>
      </body>
    </html>
  );
}
